### ISSUE TITLE
questions for my_extension.cpp

### ISSUE THREAD

**Issue by ponytaill** [lpyhdzx/DecoQuant_code#2]
Hi, could you share your `my_extension.cpp`? I don't find it in your project.
https://github.com/lpyhdzx/DecoQuant_code/blob/7184cba73f7dfec85ccea8a53b02425ab8218704/language_model/tools/torch_cuda/setup.py#L24

**Comment by lpyhdzx** [comment]
My apologies for the delayed response. This file, along with the `setup.py` in `torch_cuda`, can be safely ignored. The only package that needs to be compiled is referenced in the following line:
```shell
cd $DECOQUANT_PATH/external_modules/bdcsvd
python setup.py install
```
This is also outlined in the README.md.

**Comment by ponytaill** [comment]
Alright, thanks!
